name: CI
on:
  pull_request:
  push:
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run Nix Flake Check
      run: nix flake check

    - name: Build library and generate haddock
      run: nix build .\#nvfetcher-lib

    - name: Test CLI with nvfetcher_example.toml
      run : nix shell --command nvfetcher --config nvfetcher_example.toml

    - name: Cleanup
      run: rm -r .shake sources.nix

    - name: Test Main_example.hs
      run: nix develop --command cabal run example

    - name: Deploy generated haddock to github pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.repository_owner == 'berberman' && github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./result-doc/share/doc/nvfetcher-*/html
        cname: nvfetcher.berberman.space
  
